inline_chunk_threshold_bytes: null
get_partial_values_concurrency: null
compression: null
max_concurrent_requests: null
caching: null
storage: null
virtual_chunk_containers:
  s3://noaa-gfdl-spear-large-ensembles-pds/:
    name: null
    url_prefix: s3://noaa-gfdl-spear-large-ensembles-pds/
    store: !s3
      region: us-east-1
      endpoint_url: null
      anonymous: false
      allow_http: false
      force_path_style: false
      network_stream_timeout_seconds: 60
manifest: null
